# Generated by Django 2.2.1 on 2019-07-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTerm', '0002_auto_20190604_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('originalPort', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transferedPort', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
